name: Build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
#      checkout
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Test
        run: mvn test

  continuous-delivery:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy to heroku development entiroment
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: "53083cb5-e9d1-400f-9741-54fc664d0784"
          heroku_app_name: "ts-opensource-dev"
          heroku_email: "tropsmart18@gmail.com"

  continuous-deployment:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy to heroku production enviroment
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: "26e9942e-8c58-4c0f-a37c-c10936bf7835"
          heroku_app_name: "ts-opensource-be"
          heroku_email: "digihazard18@gmail.com"
        
        